### ISSUE TITLE
Scale images down/up to the available container space

### ISSUE THREAD

**Issue by warpech** [Polyjuice/Images#14]
Images app should scale rendered image down if they are resized with layout editor.

I propose to use a `div` with `background-size: cover` for that, instead of `img`. This gives the best scaling & cropping for minimum effort: http://codepen.io/herihehe/pen/aLwGt

**Comment by mtornwall** [comment]
+1

**Comment by miyconst** [comment]
Image now scalable to parent's container, but the problem is initial size.

To scale image I have to set:

```css
width: 100%;
height: 100%;
```

Before layout editor styles applied `width: 100%` is full screen width, this looks ugly.

The next css resizes image to full screen width and then crop 10px from center, looks ugly.
```css
div {
	min-height: 10px;
	min-width: 10px;
	height: 100%;
	width: 100%;
	background-size: cover;
	background-position: center center;
}
```

This one resizes image to full screen width and displays entire image, also looks ugly.
```css
img {
	width: 100%;
	height: 100%;
	object-fit: contain;
}
```

This one does not increase image size when parent container is greater than image.
```css
img {
	width: auto;
	height: 100%;
	object-fit: contain;
}
```
